blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://mei-nuxt3-ui.toantranmei.com
    about: Check the documentation for guides and examples.
  - name: 📚 Discord
    url: https://discord.gg/devup
    about: Consider asking questions in the `#mei-nuxt3-ui` channel.
